#!/usr/bin/env php
<?php
use Hrgruri\Saori\Console\{
    InitCommand,
    DraftCommand,
    PostCommand,
    MakeCommand,
    BuildCommand
};
require __DIR__.'/vendor/autoload.php';

$path =  __DIR__;
$app = new Symfony\Component\Console\Application();
$app->add(new InitCommand($path));
$app->add(new DraftCommand($path));
$app->add(new PostCommand($path));
$app->add(new BuildCommand($path));
$app->run();
